# .streamlit/secrets.toml

supabase_url = "https://wiycncpbnrheeweszlyd.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeWNuY3BibnJoZWV3ZXN6bHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTI1NjEyNTIsImV4cCI6MjAwODEzNzI1Mn0.23KS-qv4DxvYeVRc4h6MyfRvdoi8uy-LFkR0sU9oQzE"
